/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as TabsCreateRouteImport } from './routes/_tabs.create'
import { Route as TabsSearchRouteImport } from './routes/_tabs.search'
import { Route as TabsTrailRouteImport } from './routes/_tabs.trail'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingAccountRouteImport } from './routes/onboarding/account'
import { Route as OnboardingAgeRouteImport } from './routes/onboarding/age'
import { Route as OnboardingAssuranceRouteImport } from './routes/onboarding/assurance'
import { Route as OnboardingBuildingRouteImport } from './routes/onboarding/building'
import { Route as OnboardingFactRouteImport } from './routes/onboarding/fact'
import { Route as OnboardingInterestsRouteImport } from './routes/onboarding/interests'
import { Route as OnboardingLessonsRouteImport } from './routes/onboarding/lessons'
import { Route as OnboardingMeetRouteImport } from './routes/onboarding/meet'
import { Route as OnboardingPaywallRouteImport } from './routes/onboarding/paywall'
import { Route as OnboardingPinRouteImport } from './routes/onboarding/pin'
import { Route as OnboardingPreviewRouteImport } from './routes/onboarding/preview'
import { Route as OnboardingPrioritiesRouteImport } from './routes/onboarding/priorities'
import { Route as OnboardingReadingRouteImport } from './routes/onboarding/reading'
import { Route as OnboardingScreenTimeRouteImport } from './routes/onboarding/screen-time'
import { Route as OnboardingToneRouteImport } from './routes/onboarding/tone'
import { Route as OnboardingTrustRouteImport } from './routes/onboarding/trust'
import { Route as OnboardingTryRouteImport } from './routes/onboarding/try'
import { Route as OnboardingWorriesRouteImport } from './routes/onboarding/worries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const TabsCreateRoute = TabsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TabsRoute,
} as any)
const TabsSearchRoute = TabsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => TabsRoute,
} as any)
const TabsTrailRoute = TabsTrailRouteImport.update({
  id: '/trail',
  path: '/trail',
  getParentRoute: () => TabsRoute,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAccountRoute = OnboardingAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAgeRoute = OnboardingAgeRouteImport.update({
  id: '/age',
  path: '/age',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAssuranceRoute = OnboardingAssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBuildingRoute = OnboardingBuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingFactRoute = OnboardingFactRouteImport.update({
  id: '/fact',
  path: '/fact',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingInterestsRoute = OnboardingInterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLessonsRoute = OnboardingLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingMeetRoute = OnboardingMeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPaywallRoute = OnboardingPaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPinRoute = OnboardingPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPreviewRoute = OnboardingPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPrioritiesRoute = OnboardingPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingReadingRoute = OnboardingReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingScreenTimeRoute = OnboardingScreenTimeRouteImport.update({
  id: '/screen-time',
  path: '/screen-time',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingToneRoute = OnboardingToneRouteImport.update({
  id: '/tone',
  path: '/tone',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingTrustRoute = OnboardingTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingTryRoute = OnboardingTryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWorriesRoute = OnboardingWorriesRouteImport.update({
  id: '/worries',
  path: '/worries',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/parent': typeof ParentRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/create': typeof TabsCreateRoute
  '/search': typeof TabsSearchRoute
  '/trail': typeof TabsTrailRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/age': typeof OnboardingAgeRoute
  '/onboarding/assurance': typeof OnboardingAssuranceRoute
  '/onboarding/building': typeof OnboardingBuildingRoute
  '/onboarding/fact': typeof OnboardingFactRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/lessons': typeof OnboardingLessonsRoute
  '/onboarding/meet': typeof OnboardingMeetRoute
  '/onboarding/paywall': typeof OnboardingPaywallRoute
  '/onboarding/pin': typeof OnboardingPinRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/priorities': typeof OnboardingPrioritiesRoute
  '/onboarding/reading': typeof OnboardingReadingRoute
  '/onboarding/screen-time': typeof OnboardingScreenTimeRoute
  '/onboarding/tone': typeof OnboardingToneRoute
  '/onboarding/trust': typeof OnboardingTrustRoute
  '/onboarding/try': typeof OnboardingTryRoute
  '/onboarding/worries': typeof OnboardingWorriesRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/parent': typeof ParentRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/create': typeof TabsCreateRoute
  '/search': typeof TabsSearchRoute
  '/trail': typeof TabsTrailRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/age': typeof OnboardingAgeRoute
  '/onboarding/assurance': typeof OnboardingAssuranceRoute
  '/onboarding/building': typeof OnboardingBuildingRoute
  '/onboarding/fact': typeof OnboardingFactRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/lessons': typeof OnboardingLessonsRoute
  '/onboarding/meet': typeof OnboardingMeetRoute
  '/onboarding/paywall': typeof OnboardingPaywallRoute
  '/onboarding/pin': typeof OnboardingPinRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/priorities': typeof OnboardingPrioritiesRoute
  '/onboarding/reading': typeof OnboardingReadingRoute
  '/onboarding/screen-time': typeof OnboardingScreenTimeRoute
  '/onboarding/tone': typeof OnboardingToneRoute
  '/onboarding/trust': typeof OnboardingTrustRoute
  '/onboarding/try': typeof OnboardingTryRoute
  '/onboarding/worries': typeof OnboardingWorriesRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/parent': typeof ParentRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_tabs/create': typeof TabsCreateRoute
  '/_tabs/search': typeof TabsSearchRoute
  '/_tabs/trail': typeof TabsTrailRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/onboarding/account': typeof OnboardingAccountRoute
  '/onboarding/age': typeof OnboardingAgeRoute
  '/onboarding/assurance': typeof OnboardingAssuranceRoute
  '/onboarding/building': typeof OnboardingBuildingRoute
  '/onboarding/fact': typeof OnboardingFactRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/lessons': typeof OnboardingLessonsRoute
  '/onboarding/meet': typeof OnboardingMeetRoute
  '/onboarding/paywall': typeof OnboardingPaywallRoute
  '/onboarding/pin': typeof OnboardingPinRoute
  '/onboarding/preview': typeof OnboardingPreviewRoute
  '/onboarding/priorities': typeof OnboardingPrioritiesRoute
  '/onboarding/reading': typeof OnboardingReadingRoute
  '/onboarding/screen-time': typeof OnboardingScreenTimeRoute
  '/onboarding/tone': typeof OnboardingToneRoute
  '/onboarding/trust': typeof OnboardingTrustRoute
  '/onboarding/try': typeof OnboardingTryRoute
  '/onboarding/worries': typeof OnboardingWorriesRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/parent'
    | '/.well-known/oauth-protected-resource'
    | '/create'
    | '/search'
    | '/trail'
    | '/api/generate-image'
    | '/onboarding/account'
    | '/onboarding/age'
    | '/onboarding/assurance'
    | '/onboarding/building'
    | '/onboarding/fact'
    | '/onboarding/interests'
    | '/onboarding/lessons'
    | '/onboarding/meet'
    | '/onboarding/paywall'
    | '/onboarding/pin'
    | '/onboarding/preview'
    | '/onboarding/priorities'
    | '/onboarding/reading'
    | '/onboarding/screen-time'
    | '/onboarding/tone'
    | '/onboarding/trust'
    | '/onboarding/try'
    | '/onboarding/worries'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/parent'
    | '/.well-known/oauth-protected-resource'
    | '/create'
    | '/search'
    | '/trail'
    | '/api/generate-image'
    | '/onboarding/account'
    | '/onboarding/age'
    | '/onboarding/assurance'
    | '/onboarding/building'
    | '/onboarding/fact'
    | '/onboarding/interests'
    | '/onboarding/lessons'
    | '/onboarding/meet'
    | '/onboarding/paywall'
    | '/onboarding/pin'
    | '/onboarding/preview'
    | '/onboarding/priorities'
    | '/onboarding/reading'
    | '/onboarding/screen-time'
    | '/onboarding/tone'
    | '/onboarding/trust'
    | '/onboarding/try'
    | '/onboarding/worries'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/parent'
    | '/.well-known/oauth-protected-resource'
    | '/_tabs/create'
    | '/_tabs/search'
    | '/_tabs/trail'
    | '/api/generate-image'
    | '/onboarding/account'
    | '/onboarding/age'
    | '/onboarding/assurance'
    | '/onboarding/building'
    | '/onboarding/fact'
    | '/onboarding/interests'
    | '/onboarding/lessons'
    | '/onboarding/meet'
    | '/onboarding/paywall'
    | '/onboarding/pin'
    | '/onboarding/preview'
    | '/onboarding/priorities'
    | '/onboarding/reading'
    | '/onboarding/screen-time'
    | '/onboarding/tone'
    | '/onboarding/trust'
    | '/onboarding/try'
    | '/onboarding/worries'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ParentRoute: typeof ParentRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/create': {
      id: '/_tabs/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof TabsCreateRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/search': {
      id: '/_tabs/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof TabsSearchRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/trail': {
      id: '/_tabs/trail'
      path: '/trail'
      fullPath: '/trail'
      preLoaderRoute: typeof TabsTrailRouteImport
      parentRoute: typeof TabsRoute
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/account': {
      id: '/onboarding/account'
      path: '/account'
      fullPath: '/onboarding/account'
      preLoaderRoute: typeof OnboardingAccountRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/age': {
      id: '/onboarding/age'
      path: '/age'
      fullPath: '/onboarding/age'
      preLoaderRoute: typeof OnboardingAgeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/assurance': {
      id: '/onboarding/assurance'
      path: '/assurance'
      fullPath: '/onboarding/assurance'
      preLoaderRoute: typeof OnboardingAssuranceRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/building': {
      id: '/onboarding/building'
      path: '/building'
      fullPath: '/onboarding/building'
      preLoaderRoute: typeof OnboardingBuildingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/fact': {
      id: '/onboarding/fact'
      path: '/fact'
      fullPath: '/onboarding/fact'
      preLoaderRoute: typeof OnboardingFactRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/interests': {
      id: '/onboarding/interests'
      path: '/interests'
      fullPath: '/onboarding/interests'
      preLoaderRoute: typeof OnboardingInterestsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/lessons': {
      id: '/onboarding/lessons'
      path: '/lessons'
      fullPath: '/onboarding/lessons'
      preLoaderRoute: typeof OnboardingLessonsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/meet': {
      id: '/onboarding/meet'
      path: '/meet'
      fullPath: '/onboarding/meet'
      preLoaderRoute: typeof OnboardingMeetRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/paywall': {
      id: '/onboarding/paywall'
      path: '/paywall'
      fullPath: '/onboarding/paywall'
      preLoaderRoute: typeof OnboardingPaywallRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/pin': {
      id: '/onboarding/pin'
      path: '/pin'
      fullPath: '/onboarding/pin'
      preLoaderRoute: typeof OnboardingPinRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/preview': {
      id: '/onboarding/preview'
      path: '/preview'
      fullPath: '/onboarding/preview'
      preLoaderRoute: typeof OnboardingPreviewRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/priorities': {
      id: '/onboarding/priorities'
      path: '/priorities'
      fullPath: '/onboarding/priorities'
      preLoaderRoute: typeof OnboardingPrioritiesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/reading': {
      id: '/onboarding/reading'
      path: '/reading'
      fullPath: '/onboarding/reading'
      preLoaderRoute: typeof OnboardingReadingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/screen-time': {
      id: '/onboarding/screen-time'
      path: '/screen-time'
      fullPath: '/onboarding/screen-time'
      preLoaderRoute: typeof OnboardingScreenTimeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/tone': {
      id: '/onboarding/tone'
      path: '/tone'
      fullPath: '/onboarding/tone'
      preLoaderRoute: typeof OnboardingToneRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/trust': {
      id: '/onboarding/trust'
      path: '/trust'
      fullPath: '/onboarding/trust'
      preLoaderRoute: typeof OnboardingTrustRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/try': {
      id: '/onboarding/try'
      path: '/try'
      fullPath: '/onboarding/try'
      preLoaderRoute: typeof OnboardingTryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/worries': {
      id: '/onboarding/worries'
      path: '/worries'
      fullPath: '/onboarding/worries'
      preLoaderRoute: typeof OnboardingWorriesRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface TabsRouteChildren {
  TabsCreateRoute: typeof TabsCreateRoute
  TabsSearchRoute: typeof TabsSearchRoute
  TabsTrailRoute: typeof TabsTrailRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsCreateRoute: TabsCreateRoute,
  TabsSearchRoute: TabsSearchRoute,
  TabsTrailRoute: TabsTrailRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAccountRoute: typeof OnboardingAccountRoute
  OnboardingAgeRoute: typeof OnboardingAgeRoute
  OnboardingAssuranceRoute: typeof OnboardingAssuranceRoute
  OnboardingBuildingRoute: typeof OnboardingBuildingRoute
  OnboardingFactRoute: typeof OnboardingFactRoute
  OnboardingInterestsRoute: typeof OnboardingInterestsRoute
  OnboardingLessonsRoute: typeof OnboardingLessonsRoute
  OnboardingMeetRoute: typeof OnboardingMeetRoute
  OnboardingPaywallRoute: typeof OnboardingPaywallRoute
  OnboardingPinRoute: typeof OnboardingPinRoute
  OnboardingPreviewRoute: typeof OnboardingPreviewRoute
  OnboardingPrioritiesRoute: typeof OnboardingPrioritiesRoute
  OnboardingReadingRoute: typeof OnboardingReadingRoute
  OnboardingScreenTimeRoute: typeof OnboardingScreenTimeRoute
  OnboardingToneRoute: typeof OnboardingToneRoute
  OnboardingTrustRoute: typeof OnboardingTrustRoute
  OnboardingTryRoute: typeof OnboardingTryRoute
  OnboardingWorriesRoute: typeof OnboardingWorriesRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAccountRoute: OnboardingAccountRoute,
  OnboardingAgeRoute: OnboardingAgeRoute,
  OnboardingAssuranceRoute: OnboardingAssuranceRoute,
  OnboardingBuildingRoute: OnboardingBuildingRoute,
  OnboardingFactRoute: OnboardingFactRoute,
  OnboardingInterestsRoute: OnboardingInterestsRoute,
  OnboardingLessonsRoute: OnboardingLessonsRoute,
  OnboardingMeetRoute: OnboardingMeetRoute,
  OnboardingPaywallRoute: OnboardingPaywallRoute,
  OnboardingPinRoute: OnboardingPinRoute,
  OnboardingPreviewRoute: OnboardingPreviewRoute,
  OnboardingPrioritiesRoute: OnboardingPrioritiesRoute,
  OnboardingReadingRoute: OnboardingReadingRoute,
  OnboardingScreenTimeRoute: OnboardingScreenTimeRoute,
  OnboardingToneRoute: OnboardingToneRoute,
  OnboardingTrustRoute: OnboardingTrustRoute,
  OnboardingTryRoute: OnboardingTryRoute,
  OnboardingWorriesRoute: OnboardingWorriesRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ParentRoute: ParentRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
